### PR TITLE
BugFix proxy redirect

### PR DESCRIPTION
**Pull request by rmarow**
relates to #155

### CODE REVIEW

**Review by MattF-NSIDC — APPROVED** [review]
Of course, good catch :) Did you also figure out the "new survey" link that was not working?

**Comment by rmarow** [comment]
I haven't figured out the one for new survey yet, because it's not redirecting to (`/`) like those were and it does use `url_for`. I was thinking of merging this first and deploying to QA to make sure the fix works, then looking deeper at that one.

**Comment by MattF-NSIDC** [comment]
Sounds great to me!

**Comment by MattF-NSIDC** [comment]
Woopsie, I don't know how I did that.

**Pull request merged**
